{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-app-chart.serviceAccountName" . }}  # Ім'я сервісного акаунту, генерується на основі шаблону
  labels:
    {{- include "my-app-chart.labels" . | nindent 4 }}  # Лейбли для сервісного акаунту
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}  # Анотації, якщо вони визначені у values.yaml
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default true }}  # За замовчуванням дозволити автоматичне підключення токену
{{- end }}
